### ISSUE TITLE
Update for e10s for Firefox

### ISSUE THREAD

**Issue by jonishush** [Ndragomirov/twitch-now#159] opened 2016-12-23 18:24 UTC
with Firefox now rolling out [Electrolysis (e10s)](https://blog.mozilla.org/addons/2015/11/23/test-your-add-ons-for-multi-process-firefox-compatibility/) and supporting multi-processes, I noticed Twitch Now, one of my most used addons in Chrome and now Firefox, isn't compatible according to Mozilla's [Add-on Compatibility Reporter](https://addons.mozilla.org/en-US/firefox/addon/add-on-compatibility-reporter/). Would be great if Twitch Now could be upgraded as to not cause any issues, as the number of people getting e10s rolled out is increasing.

Thanks!

**Comment by SW1FT** [comment] 2017-01-25 17:04
He said he'll look into it. Dupe of https://github.com/Ndragomirov/twitch-now/issues/153

**Comment by Ndragomirov** [comment] 2017-02-20 11:43
fixed in 2978fb2d9a22c87f14c2a87344f903b093a439a8

**Closed by Ndragomirov** 2017-02-20 11:43 UTC
